#!/usr/bin/env python3
"""
Seed database with products from German grocery stores: Aldi, Lidl, REWE
Includes generic ingredients and specific store products with pricing.
"""

import json
import sqlite3
from datetime import date

DB_PATH = "food.db"

# Store brand colors and info for card styling
STORE_INFO = {
    "aldi": {
        "name": "Aldi",
        "color": "#00005f",  # Aldi blue
        "secondary": "#ff0000",  # Aldi red accent
        "brands": [
            "Milbona",
            "Gut Bio",
            "Goldähren",
            "Meine Metzgerei",
            "Bauernglück",
            "Gut Drei Eichen",
        ],
    },
    "lidl": {
        "name": "Lidl",
        "color": "#0050aa",  # Lidl blue
        "secondary": "#fff000",  # Lidl yellow
        "brands": ["Milbona", "Bioland", "Cien", "Freeway", "Solevita", "Pikok"],
    },
    "rewe": {
        "name": "REWE",
        "color": "#cc0000",  # REWE red
        "secondary": "#ffffff",
        "brands": ["REWE Beste Wahl", "REWE Bio", "ja!", "REWE Feine Welt"],
    },
}

# Generic ingredients (the concept, not the product)
GENERIC_INGREDIENTS = [
    # Dairy
    {
        "name": "whole milk",
        "category": "dairy",
        "default_unit": "ml",
        "avg_calories": 64,
        "avg_protein": 3.4,
        "avg_carbs": 4.8,
        "avg_fat": 3.6,
        "aliases": '["vollmilch", "fresh milk", "full fat milk"]',
    },
    {
        "name": "semi-skimmed milk",
        "category": "dairy",
        "default_unit": "ml",
        "avg_calories": 47,
        "avg_protein": 3.4,
        "avg_carbs": 4.8,
        "avg_fat": 1.6,
        "aliases": '["fettarme milch", "1.5% milk"]',
    },
    {
        "name": "skimmed milk",
        "category": "dairy",
        "default_unit": "ml",
        "avg_calories": 35,
        "avg_protein": 3.5,
        "avg_carbs": 5.0,
        "avg_fat": 0.1,
        "aliases": '["magermilch", "fat free milk"]',
    },
    {
        "name": "butter",
        "category": "dairy",
        "default_unit": "g",
        "avg_calories": 717,
        "avg_protein": 0.9,
        "avg_carbs": 0.1,
        "avg_fat": 81,
        "aliases": '["unsalted butter", "salted butter"]',
    },
    {
        "name": "eggs",
        "category": "dairy",
        "default_unit": "piece",
        "avg_calories": 155,
        "avg_protein": 13,
        "avg_carbs": 1.1,
        "avg_fat": 11,
        "aliases": '["eier", "hühnereier", "chicken eggs"]',
    },
    {
        "name": "cheese",
        "category": "dairy",
        "default_unit": "g",
        "avg_calories": 350,
        "avg_protein": 25,
        "avg_carbs": 1.3,
        "avg_fat": 28,
        "aliases": '["käse"]',
    },
    {
        "name": "yogurt",
        "category": "dairy",
        "default_unit": "g",
        "avg_calories": 61,
        "avg_protein": 3.5,
        "avg_carbs": 4.7,
        "avg_fat": 3.3,
        "aliases": '["joghurt", "natural yogurt"]',
    },
    {
        "name": "cream",
        "category": "dairy",
        "default_unit": "ml",
        "avg_calories": 195,
        "avg_protein": 2.8,
        "avg_carbs": 3.7,
        "avg_fat": 19,
        "aliases": '["sahne", "heavy cream", "schlagsahne"]',
    },
    # Grains & Bakery
    {
        "name": "bread",
        "category": "grain",
        "default_unit": "g",
        "avg_calories": 265,
        "avg_protein": 9,
        "avg_carbs": 49,
        "avg_fat": 3.2,
        "aliases": '["brot", "loaf"]',
    },
    {
        "name": "flour",
        "category": "grain",
        "default_unit": "g",
        "avg_calories": 364,
        "avg_protein": 10,
        "avg_carbs": 76,
        "avg_fat": 1.0,
        "aliases": '["mehl", "all purpose flour", "weizenmehl"]',
    },
    {
        "name": "pasta",
        "category": "grain",
        "default_unit": "g",
        "avg_calories": 371,
        "avg_protein": 13,
        "avg_carbs": 75,
        "avg_fat": 1.5,
        "aliases": '["nudeln", "spaghetti", "penne"]',
    },
    {
        "name": "rice",
        "category": "grain",
        "default_unit": "g",
        "avg_calories": 130,
        "avg_protein": 2.7,
        "avg_carbs": 28,
        "avg_fat": 0.3,
        "aliases": '["reis", "basmati", "jasmine rice"]',
    },
    {
        "name": "oats",
        "category": "grain",
        "default_unit": "g",
        "avg_calories": 389,
        "avg_protein": 17,
        "avg_carbs": 66,
        "avg_fat": 7,
        "aliases": '["haferflocken", "rolled oats", "porridge oats"]',
    },
    # Produce
    {
        "name": "onion",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 40,
        "avg_protein": 1.1,
        "avg_carbs": 9,
        "avg_fat": 0.1,
        "aliases": '["zwiebel", "yellow onion"]',
    },
    {
        "name": "garlic",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 149,
        "avg_protein": 6.4,
        "avg_carbs": 33,
        "avg_fat": 0.5,
        "aliases": '["knoblauch"]',
    },
    {
        "name": "potato",
        "category": "produce",
        "default_unit": "g",
        "avg_calories": 77,
        "avg_protein": 2,
        "avg_carbs": 17,
        "avg_fat": 0.1,
        "aliases": '["kartoffel", "kartoffeln"]',
    },
    {
        "name": "tomato",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 18,
        "avg_protein": 0.9,
        "avg_carbs": 3.9,
        "avg_fat": 0.2,
        "aliases": '["tomate", "tomaten"]',
    },
    {
        "name": "carrot",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 41,
        "avg_protein": 0.9,
        "avg_carbs": 10,
        "avg_fat": 0.2,
        "aliases": '["karotte", "möhre"]',
    },
    {
        "name": "apple",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 52,
        "avg_protein": 0.3,
        "avg_carbs": 14,
        "avg_fat": 0.2,
        "aliases": '["apfel", "äpfel"]',
    },
    {
        "name": "banana",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 89,
        "avg_protein": 1.1,
        "avg_carbs": 23,
        "avg_fat": 0.3,
        "aliases": '["banane"]',
    },
    {
        "name": "lemon",
        "category": "produce",
        "default_unit": "piece",
        "avg_calories": 29,
        "avg_protein": 1.1,
        "avg_carbs": 9,
        "avg_fat": 0.3,
        "aliases": '["zitrone"]',
    },
    # Meat & Protein
    {
        "name": "chicken breast",
        "category": "meat",
        "default_unit": "g",
        "avg_calories": 165,
        "avg_protein": 31,
        "avg_carbs": 0,
        "avg_fat": 3.6,
        "aliases": '["hähnchenbrust", "hühnerbrust"]',
    },
    {
        "name": "ground beef",
        "category": "meat",
        "default_unit": "g",
        "avg_calories": 250,
        "avg_protein": 26,
        "avg_carbs": 0,
        "avg_fat": 15,
        "aliases": '["hackfleisch", "rinderhack", "mince"]',
    },
    {
        "name": "bacon",
        "category": "meat",
        "default_unit": "g",
        "avg_calories": 541,
        "avg_protein": 37,
        "avg_carbs": 1.4,
        "avg_fat": 42,
        "aliases": '["speck", "frühstücksspeck"]',
    },
    {
        "name": "salmon",
        "category": "meat",
        "default_unit": "g",
        "avg_calories": 208,
        "avg_protein": 20,
        "avg_carbs": 0,
        "avg_fat": 13,
        "aliases": '["lachs"]',
    },
    # Pantry Staples
    {
        "name": "olive oil",
        "category": "pantry",
        "default_unit": "ml",
        "avg_calories": 884,
        "avg_protein": 0,
        "avg_carbs": 0,
        "avg_fat": 100,
        "aliases": '["olivenöl", "extra virgin olive oil"]',
    },
    {
        "name": "vegetable oil",
        "category": "pantry",
        "default_unit": "ml",
        "avg_calories": 884,
        "avg_protein": 0,
        "avg_carbs": 0,
        "avg_fat": 100,
        "aliases": '["sonnenblumenöl", "rapsöl", "sunflower oil"]',
    },
    {
        "name": "sugar",
        "category": "pantry",
        "default_unit": "g",
        "avg_calories": 387,
        "avg_protein": 0,
        "avg_carbs": 100,
        "avg_fat": 0,
        "aliases": '["zucker", "white sugar"]',
    },
    {
        "name": "salt",
        "category": "spice",
        "default_unit": "g",
        "avg_calories": 0,
        "avg_protein": 0,
        "avg_carbs": 0,
        "avg_fat": 0,
        "aliases": '["salz", "table salt", "sea salt"]',
    },
    {
        "name": "pepper",
        "category": "spice",
        "default_unit": "g",
        "avg_calories": 251,
        "avg_protein": 10,
        "avg_carbs": 64,
        "avg_fat": 3.3,
        "aliases": '["pfeffer", "black pepper"]',
    },
    {
        "name": "canned tomatoes",
        "category": "pantry",
        "default_unit": "g",
        "avg_calories": 18,
        "avg_protein": 0.9,
        "avg_carbs": 3.9,
        "avg_fat": 0.1,
        "aliases": '["dosentomaten", "gehackte tomaten", "chopped tomatoes"]',
    },
    {
        "name": "chicken stock",
        "category": "pantry",
        "default_unit": "ml",
        "avg_calories": 4,
        "avg_protein": 0.5,
        "avg_carbs": 0.3,
        "avg_fat": 0,
        "aliases": '["hühnerbrühe", "chicken broth"]',
    },
]

# Actual store products with real barcodes and prices (German market)
# Prices are approximate as of 2024
STORE_PRODUCTS = [
    # ============ ALDI PRODUCTS ============
    # Dairy - Aldi
    {
        "barcode": "4061458007139",
        "name": "Frische Vollmilch 3.5%",
        "brand": "Milbona",
        "store": "aldi",
        "ingredient_name": "whole milk",
        "category": "dairy",
        "subcategory": "milk",
        "storage_type": "fridge",
        "calories": 64,
        "protein": 3.4,
        "carbs": 4.8,
        "fat": 3.6,
        "fiber": 0,
        "sodium": 44,
        "sugar": 4.8,
        "saturated_fat": 2.3,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.15,
        "price_per_kg": 1.15,
    },
    {
        "barcode": "4061458023207",
        "name": "Fettarme Milch 1.5%",
        "brand": "Milbona",
        "store": "aldi",
        "ingredient_name": "semi-skimmed milk",
        "category": "dairy",
        "subcategory": "milk",
        "storage_type": "fridge",
        "calories": 47,
        "protein": 3.4,
        "carbs": 4.9,
        "fat": 1.5,
        "fiber": 0,
        "sodium": 44,
        "sugar": 4.9,
        "saturated_fat": 1.0,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.09,
        "price_per_kg": 1.09,
    },
    {
        "barcode": "4061458008792",
        "name": "Deutsche Markenbutter",
        "brand": "Milbona",
        "store": "aldi",
        "ingredient_name": "butter",
        "category": "dairy",
        "subcategory": "butter",
        "storage_type": "fridge",
        "calories": 741,
        "protein": 0.6,
        "carbs": 0.6,
        "fat": 82,
        "fiber": 0,
        "sodium": 11,
        "sugar": 0.6,
        "saturated_fat": 54,
        "package_weight_g": 250,
        "package_unit": "g",
        "price": 1.99,
        "price_per_kg": 7.96,
    },
    {
        "barcode": "4061458018456",
        "name": "Frische Eier Bodenhaltung 10er",
        "brand": "Gut Drei Eichen",
        "store": "aldi",
        "ingredient_name": "eggs",
        "category": "dairy",
        "subcategory": "eggs",
        "storage_type": "fridge",
        "calories": 155,
        "protein": 13,
        "carbs": 1.1,
        "fat": 11,
        "fiber": 0,
        "sodium": 124,
        "sugar": 1.1,
        "saturated_fat": 3.3,
        "package_weight_g": 600,
        "package_unit": "g",
        "price": 1.79,
        "price_per_kg": 2.98,
    },
    {
        "barcode": "4061458046336",
        "name": "Gouda jung",
        "brand": "Milbona",
        "store": "aldi",
        "ingredient_name": "cheese",
        "category": "dairy",
        "subcategory": "cheese",
        "storage_type": "fridge",
        "calories": 356,
        "protein": 24,
        "carbs": 0.1,
        "fat": 29,
        "fiber": 0,
        "sodium": 620,
        "sugar": 0.1,
        "saturated_fat": 18,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 2.79,
        "price_per_kg": 6.98,
    },
    {
        "barcode": "4061458052306",
        "name": "Naturjoghurt 3.5%",
        "brand": "Milbona",
        "store": "aldi",
        "ingredient_name": "yogurt",
        "category": "dairy",
        "subcategory": "yogurt",
        "storage_type": "fridge",
        "calories": 69,
        "protein": 4.0,
        "carbs": 4.5,
        "fat": 3.8,
        "fiber": 0,
        "sodium": 50,
        "sugar": 4.5,
        "saturated_fat": 2.4,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.75,
        "price_per_kg": 1.50,
    },
    {
        "barcode": "4061458029155",
        "name": "Schlagsahne",
        "brand": "Milbona",
        "store": "aldi",
        "ingredient_name": "cream",
        "category": "dairy",
        "subcategory": "cream",
        "storage_type": "fridge",
        "calories": 310,
        "protein": 2.4,
        "carbs": 3.2,
        "fat": 32,
        "fiber": 0,
        "sodium": 35,
        "sugar": 3.2,
        "saturated_fat": 20,
        "package_weight_g": 200,
        "package_unit": "ml",
        "price": 0.69,
        "price_per_kg": 3.45,
    },
    # Grains & Bakery - Aldi
    {
        "barcode": "4061458048350",
        "name": "Weizenmehl Type 405",
        "brand": "Goldähren",
        "store": "aldi",
        "ingredient_name": "flour",
        "category": "grain",
        "subcategory": "flour",
        "storage_type": "pantry",
        "calories": 348,
        "protein": 10,
        "carbs": 72,
        "fat": 1.0,
        "fiber": 3.2,
        "sodium": 2,
        "sugar": 0.3,
        "saturated_fat": 0.2,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 0.59,
        "price_per_kg": 0.59,
    },
    {
        "barcode": "4061458066101",
        "name": "Spaghetti No. 5",
        "brand": "Cucina",
        "store": "aldi",
        "ingredient_name": "pasta",
        "category": "grain",
        "subcategory": "pasta",
        "storage_type": "pantry",
        "calories": 359,
        "protein": 13,
        "carbs": 71,
        "fat": 1.5,
        "fiber": 3.0,
        "sodium": 5,
        "sugar": 3.0,
        "saturated_fat": 0.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.79,
        "price_per_kg": 1.58,
    },
    {
        "barcode": "4061458068532",
        "name": "Langkorn Parboiled Reis",
        "brand": "Golden Sun",
        "store": "aldi",
        "ingredient_name": "rice",
        "category": "grain",
        "subcategory": "rice",
        "storage_type": "pantry",
        "calories": 350,
        "protein": 7.0,
        "carbs": 78,
        "fat": 0.6,
        "fiber": 1.4,
        "sodium": 3,
        "sugar": 0.2,
        "saturated_fat": 0.2,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 1.79,
        "price_per_kg": 1.79,
    },
    {
        "barcode": "4061458038744",
        "name": "Haferflocken zart",
        "brand": "Goldähren",
        "store": "aldi",
        "ingredient_name": "oats",
        "category": "grain",
        "subcategory": "oats",
        "storage_type": "pantry",
        "calories": 372,
        "protein": 13,
        "carbs": 59,
        "fat": 7.0,
        "fiber": 10,
        "sodium": 7,
        "sugar": 1.0,
        "saturated_fat": 1.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.59,
        "price_per_kg": 1.18,
    },
    # Meat - Aldi
    {
        "barcode": "4061458057318",
        "name": "Hähnchenbrustfilet",
        "brand": "Meine Metzgerei",
        "store": "aldi",
        "ingredient_name": "chicken breast",
        "category": "meat",
        "subcategory": "poultry",
        "storage_type": "fridge",
        "calories": 165,
        "protein": 31,
        "carbs": 0,
        "fat": 3.6,
        "fiber": 0,
        "sodium": 75,
        "sugar": 0,
        "saturated_fat": 1.0,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 4.49,
        "price_per_kg": 11.23,
    },
    {
        "barcode": "4061458014441",
        "name": "Rinderhackfleisch",
        "brand": "Meine Metzgerei",
        "store": "aldi",
        "ingredient_name": "ground beef",
        "category": "meat",
        "subcategory": "beef",
        "storage_type": "fridge",
        "calories": 212,
        "protein": 20,
        "carbs": 0,
        "fat": 14,
        "fiber": 0,
        "sodium": 68,
        "sugar": 0,
        "saturated_fat": 5.5,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 4.29,
        "price_per_kg": 8.58,
    },
    {
        "barcode": "4061458095792",
        "name": "Frühstücksspeck",
        "brand": "Meine Metzgerei",
        "store": "aldi",
        "ingredient_name": "bacon",
        "category": "meat",
        "subcategory": "pork",
        "storage_type": "fridge",
        "calories": 290,
        "protein": 15,
        "carbs": 1.0,
        "fat": 25,
        "fiber": 0,
        "sodium": 1200,
        "sugar": 0.5,
        "saturated_fat": 9.5,
        "package_weight_g": 200,
        "package_unit": "g",
        "price": 1.99,
        "price_per_kg": 9.95,
    },
    # Pantry - Aldi
    {
        "barcode": "4061458010122",
        "name": "Natives Olivenöl Extra",
        "brand": "Cantinelle",
        "store": "aldi",
        "ingredient_name": "olive oil",
        "category": "pantry",
        "subcategory": "oil",
        "storage_type": "pantry",
        "calories": 824,
        "protein": 0,
        "carbs": 0,
        "fat": 92,
        "fiber": 0,
        "sodium": 0,
        "sugar": 0,
        "saturated_fat": 13,
        "package_weight_g": 750,
        "package_unit": "ml",
        "price": 4.49,
        "price_per_kg": 5.99,
    },
    {
        "barcode": "4061458007467",
        "name": "Sonnenblumenöl",
        "brand": "Bellasan",
        "store": "aldi",
        "ingredient_name": "vegetable oil",
        "category": "pantry",
        "subcategory": "oil",
        "storage_type": "pantry",
        "calories": 828,
        "protein": 0,
        "carbs": 0,
        "fat": 92,
        "fiber": 0,
        "sodium": 0,
        "sugar": 0,
        "saturated_fat": 10,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.79,
        "price_per_kg": 1.79,
    },
    {
        "barcode": "4061458004954",
        "name": "Feiner Zucker",
        "brand": "Südzucker",
        "store": "aldi",
        "ingredient_name": "sugar",
        "category": "pantry",
        "subcategory": "sugar",
        "storage_type": "pantry",
        "calories": 400,
        "protein": 0,
        "carbs": 100,
        "fat": 0,
        "fiber": 0,
        "sodium": 0,
        "sugar": 100,
        "saturated_fat": 0,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 0.99,
        "price_per_kg": 0.99,
    },
    {
        "barcode": "4061458067559",
        "name": "Gehackte Tomaten",
        "brand": "Cucina",
        "store": "aldi",
        "ingredient_name": "canned tomatoes",
        "category": "pantry",
        "subcategory": "canned",
        "storage_type": "pantry",
        "calories": 26,
        "protein": 1.3,
        "carbs": 4.1,
        "fat": 0.2,
        "fiber": 1.0,
        "sodium": 50,
        "sugar": 3.8,
        "saturated_fat": 0,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 0.49,
        "price_per_kg": 1.23,
    },
    # ============ LIDL PRODUCTS ============
    # Dairy - Lidl
    {
        "barcode": "20135754",
        "name": "Frische Vollmilch 3.5%",
        "brand": "Milbona",
        "store": "lidl",
        "ingredient_name": "whole milk",
        "category": "dairy",
        "subcategory": "milk",
        "storage_type": "fridge",
        "calories": 64,
        "protein": 3.3,
        "carbs": 4.7,
        "fat": 3.5,
        "fiber": 0,
        "sodium": 43,
        "sugar": 4.7,
        "saturated_fat": 2.2,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.09,
        "price_per_kg": 1.09,
    },
    {
        "barcode": "20037433",
        "name": "Fettarme H-Milch 1.5%",
        "brand": "Milbona",
        "store": "lidl",
        "ingredient_name": "semi-skimmed milk",
        "category": "dairy",
        "subcategory": "milk",
        "storage_type": "fridge",
        "calories": 46,
        "protein": 3.4,
        "carbs": 4.8,
        "fat": 1.5,
        "fiber": 0,
        "sodium": 45,
        "sugar": 4.8,
        "saturated_fat": 1.0,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 0.99,
        "price_per_kg": 0.99,
    },
    {
        "barcode": "20894364",
        "name": "Deutsche Markenbutter",
        "brand": "Milbona",
        "store": "lidl",
        "ingredient_name": "butter",
        "category": "dairy",
        "subcategory": "butter",
        "storage_type": "fridge",
        "calories": 744,
        "protein": 0.5,
        "carbs": 0.5,
        "fat": 82,
        "fiber": 0,
        "sodium": 10,
        "sugar": 0.5,
        "saturated_fat": 55,
        "package_weight_g": 250,
        "package_unit": "g",
        "price": 1.95,
        "price_per_kg": 7.80,
    },
    {
        "barcode": "20012690",
        "name": "Eier Freilandhaltung 10er",
        "brand": "Landfreude",
        "store": "lidl",
        "ingredient_name": "eggs",
        "category": "dairy",
        "subcategory": "eggs",
        "storage_type": "fridge",
        "calories": 155,
        "protein": 13,
        "carbs": 1.1,
        "fat": 11,
        "fiber": 0,
        "sodium": 124,
        "sugar": 1.1,
        "saturated_fat": 3.3,
        "package_weight_g": 600,
        "package_unit": "g",
        "price": 2.19,
        "price_per_kg": 3.65,
    },
    {
        "barcode": "20045337",
        "name": "Gouda jung in Scheiben",
        "brand": "Milbona",
        "store": "lidl",
        "ingredient_name": "cheese",
        "category": "dairy",
        "subcategory": "cheese",
        "storage_type": "fridge",
        "calories": 343,
        "protein": 23,
        "carbs": 0,
        "fat": 28,
        "fiber": 0,
        "sodium": 600,
        "sugar": 0,
        "saturated_fat": 18,
        "package_weight_g": 250,
        "package_unit": "g",
        "price": 1.79,
        "price_per_kg": 7.16,
    },
    {
        "barcode": "20163924",
        "name": "Natur Joghurt mild 3.5%",
        "brand": "Milbona",
        "store": "lidl",
        "ingredient_name": "yogurt",
        "category": "dairy",
        "subcategory": "yogurt",
        "storage_type": "fridge",
        "calories": 67,
        "protein": 3.8,
        "carbs": 4.6,
        "fat": 3.5,
        "fiber": 0,
        "sodium": 48,
        "sugar": 4.6,
        "saturated_fat": 2.2,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.69,
        "price_per_kg": 1.38,
    },
    # Grains & Bakery - Lidl
    {
        "barcode": "20095832",
        "name": "Weizenmehl Type 405",
        "brand": "Belbake",
        "store": "lidl",
        "ingredient_name": "flour",
        "category": "grain",
        "subcategory": "flour",
        "storage_type": "pantry",
        "calories": 348,
        "protein": 10,
        "carbs": 72,
        "fat": 1.0,
        "fiber": 3.2,
        "sodium": 2,
        "sugar": 0.3,
        "saturated_fat": 0.2,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 0.55,
        "price_per_kg": 0.55,
    },
    {
        "barcode": "20028618",
        "name": "Spaghetti",
        "brand": "Combino",
        "store": "lidl",
        "ingredient_name": "pasta",
        "category": "grain",
        "subcategory": "pasta",
        "storage_type": "pantry",
        "calories": 359,
        "protein": 12,
        "carbs": 72,
        "fat": 1.5,
        "fiber": 3.0,
        "sodium": 5,
        "sugar": 2.5,
        "saturated_fat": 0.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.75,
        "price_per_kg": 1.50,
    },
    {
        "barcode": "20008924",
        "name": "Basmati Reis",
        "brand": "Golden Sun",
        "store": "lidl",
        "ingredient_name": "rice",
        "category": "grain",
        "subcategory": "rice",
        "storage_type": "pantry",
        "calories": 351,
        "protein": 7.5,
        "carbs": 77,
        "fat": 1.0,
        "fiber": 1.4,
        "sodium": 3,
        "sugar": 0.2,
        "saturated_fat": 0.2,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 1.99,
        "price_per_kg": 1.99,
    },
    {
        "barcode": "20096617",
        "name": "Zarte Haferflocken",
        "brand": "Crownfield",
        "store": "lidl",
        "ingredient_name": "oats",
        "category": "grain",
        "subcategory": "oats",
        "storage_type": "pantry",
        "calories": 372,
        "protein": 13,
        "carbs": 58,
        "fat": 7.0,
        "fiber": 10,
        "sodium": 5,
        "sugar": 1.1,
        "saturated_fat": 1.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.55,
        "price_per_kg": 1.10,
    },
    # Meat - Lidl
    {
        "barcode": "20186381",
        "name": "Hähnchenbrust Natur",
        "brand": "Landjunker",
        "store": "lidl",
        "ingredient_name": "chicken breast",
        "category": "meat",
        "subcategory": "poultry",
        "storage_type": "fridge",
        "calories": 107,
        "protein": 23,
        "carbs": 0.5,
        "fat": 1.5,
        "fiber": 0,
        "sodium": 70,
        "sugar": 0.5,
        "saturated_fat": 0.5,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 3.99,
        "price_per_kg": 9.98,
    },
    {
        "barcode": "20025419",
        "name": "Hackfleisch gemischt",
        "brand": "Landjunker",
        "store": "lidl",
        "ingredient_name": "ground beef",
        "category": "meat",
        "subcategory": "beef",
        "storage_type": "fridge",
        "calories": 247,
        "protein": 17,
        "carbs": 0.5,
        "fat": 20,
        "fiber": 0,
        "sodium": 65,
        "sugar": 0,
        "saturated_fat": 8.0,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 3.99,
        "price_per_kg": 7.98,
    },
    # Pantry - Lidl
    {
        "barcode": "20135808",
        "name": "Natives Olivenöl Extra",
        "brand": "Primadonna",
        "store": "lidl",
        "ingredient_name": "olive oil",
        "category": "pantry",
        "subcategory": "oil",
        "storage_type": "pantry",
        "calories": 824,
        "protein": 0,
        "carbs": 0,
        "fat": 92,
        "fiber": 0,
        "sodium": 0,
        "sugar": 0,
        "saturated_fat": 14,
        "package_weight_g": 750,
        "package_unit": "ml",
        "price": 3.99,
        "price_per_kg": 5.32,
    },
    {
        "barcode": "20017672",
        "name": "Sonnenblumenöl",
        "brand": "Vita D'or",
        "store": "lidl",
        "ingredient_name": "vegetable oil",
        "category": "pantry",
        "subcategory": "oil",
        "storage_type": "pantry",
        "calories": 828,
        "protein": 0,
        "carbs": 0,
        "fat": 92,
        "fiber": 0,
        "sodium": 0,
        "sugar": 0,
        "saturated_fat": 11,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.69,
        "price_per_kg": 1.69,
    },
    {
        "barcode": "20029667",
        "name": "Feine Zucker",
        "brand": "Diamant",
        "store": "lidl",
        "ingredient_name": "sugar",
        "category": "pantry",
        "subcategory": "sugar",
        "storage_type": "pantry",
        "calories": 400,
        "protein": 0,
        "carbs": 100,
        "fat": 0,
        "fiber": 0,
        "sodium": 0,
        "sugar": 100,
        "saturated_fat": 0,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 0.95,
        "price_per_kg": 0.95,
    },
    {
        "barcode": "20014855",
        "name": "Gehackte Tomaten",
        "brand": "Freshona",
        "store": "lidl",
        "ingredient_name": "canned tomatoes",
        "category": "pantry",
        "subcategory": "canned",
        "storage_type": "pantry",
        "calories": 24,
        "protein": 1.2,
        "carbs": 4.0,
        "fat": 0.2,
        "fiber": 0.9,
        "sodium": 45,
        "sugar": 3.5,
        "saturated_fat": 0,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 0.45,
        "price_per_kg": 1.13,
    },
    # ============ REWE PRODUCTS ============
    # Dairy - REWE
    {
        "barcode": "4388840000012",
        "name": "Frische Vollmilch 3.5%",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "whole milk",
        "category": "dairy",
        "subcategory": "milk",
        "storage_type": "fridge",
        "calories": 64,
        "protein": 3.3,
        "carbs": 4.8,
        "fat": 3.5,
        "fiber": 0,
        "sodium": 44,
        "sugar": 4.8,
        "saturated_fat": 2.3,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.19,
        "price_per_kg": 1.19,
    },
    {
        "barcode": "4388840008148",
        "name": "Fettarme Milch 1.5%",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "semi-skimmed milk",
        "category": "dairy",
        "subcategory": "milk",
        "storage_type": "fridge",
        "calories": 47,
        "protein": 3.4,
        "carbs": 4.9,
        "fat": 1.5,
        "fiber": 0,
        "sodium": 45,
        "sugar": 4.9,
        "saturated_fat": 1.0,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.15,
        "price_per_kg": 1.15,
    },
    {
        "barcode": "4388840013210",
        "name": "Deutsche Markenbutter",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "butter",
        "category": "dairy",
        "subcategory": "butter",
        "storage_type": "fridge",
        "calories": 744,
        "protein": 0.6,
        "carbs": 0.6,
        "fat": 82,
        "fiber": 0,
        "sodium": 11,
        "sugar": 0.6,
        "saturated_fat": 54,
        "package_weight_g": 250,
        "package_unit": "g",
        "price": 2.29,
        "price_per_kg": 9.16,
    },
    {
        "barcode": "4388840019472",
        "name": "Bio Eier 10er",
        "brand": "REWE Bio",
        "store": "rewe",
        "ingredient_name": "eggs",
        "category": "dairy",
        "subcategory": "eggs",
        "storage_type": "fridge",
        "calories": 155,
        "protein": 13,
        "carbs": 1.1,
        "fat": 11,
        "fiber": 0,
        "sodium": 124,
        "sugar": 1.1,
        "saturated_fat": 3.3,
        "package_weight_g": 600,
        "package_unit": "g",
        "price": 3.49,
        "price_per_kg": 5.82,
    },
    {
        "barcode": "4388840029112",
        "name": "Gouda jung",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "cheese",
        "category": "dairy",
        "subcategory": "cheese",
        "storage_type": "fridge",
        "calories": 356,
        "protein": 24,
        "carbs": 0.1,
        "fat": 29,
        "fiber": 0,
        "sodium": 620,
        "sugar": 0.1,
        "saturated_fat": 18,
        "package_weight_g": 300,
        "package_unit": "g",
        "price": 2.49,
        "price_per_kg": 8.30,
    },
    {
        "barcode": "4388840034567",
        "name": "Bio Naturjoghurt",
        "brand": "REWE Bio",
        "store": "rewe",
        "ingredient_name": "yogurt",
        "category": "dairy",
        "subcategory": "yogurt",
        "storage_type": "fridge",
        "calories": 63,
        "protein": 5.0,
        "carbs": 4.2,
        "fat": 3.5,
        "fiber": 0,
        "sodium": 45,
        "sugar": 4.2,
        "saturated_fat": 2.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 1.29,
        "price_per_kg": 2.58,
    },
    # Grains & Bakery - REWE
    {
        "barcode": "4388840051234",
        "name": "Weizenmehl Type 405",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "flour",
        "category": "grain",
        "subcategory": "flour",
        "storage_type": "pantry",
        "calories": 348,
        "protein": 10,
        "carbs": 72,
        "fat": 1.0,
        "fiber": 3.2,
        "sodium": 2,
        "sugar": 0.3,
        "saturated_fat": 0.2,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 0.69,
        "price_per_kg": 0.69,
    },
    {
        "barcode": "4388840055678",
        "name": "Spaghetti No. 5",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "pasta",
        "category": "grain",
        "subcategory": "pasta",
        "storage_type": "pantry",
        "calories": 359,
        "protein": 13,
        "carbs": 71,
        "fat": 1.5,
        "fiber": 3.0,
        "sodium": 5,
        "sugar": 3.0,
        "saturated_fat": 0.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.99,
        "price_per_kg": 1.98,
    },
    {
        "barcode": "4388840059876",
        "name": "Basmati Reis",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "rice",
        "category": "grain",
        "subcategory": "rice",
        "storage_type": "pantry",
        "calories": 351,
        "protein": 7.5,
        "carbs": 77,
        "fat": 1.0,
        "fiber": 1.4,
        "sodium": 3,
        "sugar": 0.2,
        "saturated_fat": 0.2,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 1.49,
        "price_per_kg": 2.98,
    },
    {
        "barcode": "4388840063456",
        "name": "Bio Haferflocken",
        "brand": "REWE Bio",
        "store": "rewe",
        "ingredient_name": "oats",
        "category": "grain",
        "subcategory": "oats",
        "storage_type": "pantry",
        "calories": 372,
        "protein": 13,
        "carbs": 59,
        "fat": 7.0,
        "fiber": 10,
        "sodium": 7,
        "sugar": 1.0,
        "saturated_fat": 1.3,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.99,
        "price_per_kg": 1.98,
    },
    # Meat - REWE
    {
        "barcode": "4388840071234",
        "name": "Hähnchenbrust",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "chicken breast",
        "category": "meat",
        "subcategory": "poultry",
        "storage_type": "fridge",
        "calories": 110,
        "protein": 23,
        "carbs": 0,
        "fat": 2.0,
        "fiber": 0,
        "sodium": 70,
        "sugar": 0,
        "saturated_fat": 0.6,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 5.99,
        "price_per_kg": 14.98,
    },
    {
        "barcode": "4388840075678",
        "name": "Bio Rinderhack",
        "brand": "REWE Bio",
        "store": "rewe",
        "ingredient_name": "ground beef",
        "category": "meat",
        "subcategory": "beef",
        "storage_type": "fridge",
        "calories": 170,
        "protein": 20,
        "carbs": 0,
        "fat": 10,
        "fiber": 0,
        "sodium": 65,
        "sugar": 0,
        "saturated_fat": 4.5,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 5.49,
        "price_per_kg": 13.73,
    },
    {
        "barcode": "4388840079012",
        "name": "Frühstücksspeck",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "bacon",
        "category": "meat",
        "subcategory": "pork",
        "storage_type": "fridge",
        "calories": 285,
        "protein": 15,
        "carbs": 1.0,
        "fat": 25,
        "fiber": 0,
        "sodium": 1150,
        "sugar": 0.5,
        "saturated_fat": 9.0,
        "package_weight_g": 150,
        "package_unit": "g",
        "price": 2.29,
        "price_per_kg": 15.27,
    },
    {
        "barcode": "4388840083456",
        "name": "Lachs Filet",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "salmon",
        "category": "meat",
        "subcategory": "fish",
        "storage_type": "fridge",
        "calories": 206,
        "protein": 20,
        "carbs": 0,
        "fat": 14,
        "fiber": 0,
        "sodium": 50,
        "sugar": 0,
        "saturated_fat": 2.5,
        "package_weight_g": 250,
        "package_unit": "g",
        "price": 5.99,
        "price_per_kg": 23.96,
    },
    # Pantry - REWE
    {
        "barcode": "4388840091234",
        "name": "Bio Olivenöl Extra",
        "brand": "REWE Bio",
        "store": "rewe",
        "ingredient_name": "olive oil",
        "category": "pantry",
        "subcategory": "oil",
        "storage_type": "pantry",
        "calories": 824,
        "protein": 0,
        "carbs": 0,
        "fat": 92,
        "fiber": 0,
        "sodium": 0,
        "sugar": 0,
        "saturated_fat": 13,
        "package_weight_g": 500,
        "package_unit": "ml",
        "price": 4.99,
        "price_per_kg": 9.98,
    },
    {
        "barcode": "4388840095678",
        "name": "Sonnenblumenöl",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "vegetable oil",
        "category": "pantry",
        "subcategory": "oil",
        "storage_type": "pantry",
        "calories": 828,
        "protein": 0,
        "carbs": 0,
        "fat": 92,
        "fiber": 0,
        "sodium": 0,
        "sugar": 0,
        "saturated_fat": 10,
        "package_weight_g": 1000,
        "package_unit": "ml",
        "price": 1.99,
        "price_per_kg": 1.99,
    },
    {
        "barcode": "4388840099012",
        "name": "Feiner Zucker",
        "brand": "ja!",
        "store": "rewe",
        "ingredient_name": "sugar",
        "category": "pantry",
        "subcategory": "sugar",
        "storage_type": "pantry",
        "calories": 400,
        "protein": 0,
        "carbs": 100,
        "fat": 0,
        "fiber": 0,
        "sodium": 0,
        "sugar": 100,
        "saturated_fat": 0,
        "package_weight_g": 1000,
        "package_unit": "g",
        "price": 0.89,
        "price_per_kg": 0.89,
    },
    {
        "barcode": "4388840103456",
        "name": "Gehackte Tomaten",
        "brand": "REWE Beste Wahl",
        "store": "rewe",
        "ingredient_name": "canned tomatoes",
        "category": "pantry",
        "subcategory": "canned",
        "storage_type": "pantry",
        "calories": 25,
        "protein": 1.3,
        "carbs": 4.0,
        "fat": 0.2,
        "fiber": 1.0,
        "sodium": 50,
        "sugar": 3.5,
        "saturated_fat": 0,
        "package_weight_g": 400,
        "package_unit": "g",
        "price": 0.55,
        "price_per_kg": 1.38,
    },
    # Spices - All stores
    {
        "barcode": "4061458087193",
        "name": "Meersalz",
        "brand": "Le Gusto",
        "store": "aldi",
        "ingredient_name": "salt",
        "category": "spice",
        "subcategory": "salt",
        "storage_type": "spice_rack",
        "calories": 0,
        "protein": 0,
        "carbs": 0,
        "fat": 0,
        "fiber": 0,
        "sodium": 38758,
        "sugar": 0,
        "saturated_fat": 0,
        "package_weight_g": 500,
        "package_unit": "g",
        "price": 0.49,
        "price_per_kg": 0.98,
    },
    {
        "barcode": "20045892",
        "name": "Schwarzer Pfeffer gemahlen",
        "brand": "Kania",
        "store": "lidl",
        "ingredient_name": "pepper",
        "category": "spice",
        "subcategory": "pepper",
        "storage_type": "spice_rack",
        "calories": 251,
        "protein": 10,
        "carbs": 64,
        "fat": 3.3,
        "fiber": 25,
        "sodium": 20,
        "sugar": 0.6,
        "saturated_fat": 1.4,
        "package_weight_g": 50,
        "package_unit": "g",
        "price": 0.99,
        "price_per_kg": 19.80,
    },
    {
        "barcode": "4388840107890",
        "name": "Bio Meersalz",
        "brand": "REWE Bio",
        "store": "rewe",
        "ingredient_name": "salt",
        "category": "spice",
        "subcategory": "salt",
        "storage_type": "spice_rack",
        "calories": 0,
        "protein": 0,
        "carbs": 0,
        "fat": 0,
        "fiber": 0,
        "sodium": 38758,
        "sugar": 0,
        "saturated_fat": 0,
        "package_weight_g": 250,
        "package_unit": "g",
        "price": 0.79,
        "price_per_kg": 3.16,
    },
]


def seed_database():
    """Seed the database with ingredients and products."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Create tables if they don't exist (the Flask app should have done this)
    print("Ensuring generic_ingredients table exists...")
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS generic_ingredients (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            category TEXT,
            default_unit TEXT,
            avg_calories REAL DEFAULT 0,
            avg_protein REAL DEFAULT 0,
            avg_carbs REAL DEFAULT 0,
            avg_fat REAL DEFAULT 0,
            aliases TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """
    )

    # Add new columns to pantry_products if they don't exist
    print("Adding new columns to pantry_products if needed...")
    new_columns = [
        ("store", "TEXT"),
        ("store_product_id", "TEXT"),
        ("ingredient_id", "INTEGER"),
        ("subcategory", "TEXT"),
        ("storage_type", "TEXT DEFAULT 'pantry'"),
        ("saturated_fat", "REAL DEFAULT 0"),
        ("package_unit", "TEXT"),
        ("price_per_kg", "REAL"),
        ("currency", "TEXT DEFAULT 'EUR'"),
        ("last_price_update", "DATE"),
    ]

    for col_name, col_type in new_columns:
        try:
            cursor.execute(f"ALTER TABLE pantry_products ADD COLUMN {col_name} {col_type}")
            print(f"  Added column: {col_name}")
        except sqlite3.OperationalError:
            pass  # Column already exists

    # Seed generic ingredients
    print("\nSeeding generic ingredients...")
    ingredient_ids = {}
    for ing in GENERIC_INGREDIENTS:
        try:
            cursor.execute(
                """
                INSERT OR REPLACE INTO generic_ingredients
                (name, category, default_unit, avg_calories, avg_protein, avg_carbs, avg_fat, aliases)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
                (
                    ing["name"],
                    ing["category"],
                    ing["default_unit"],
                    ing["avg_calories"],
                    ing["avg_protein"],
                    ing["avg_carbs"],
                    ing["avg_fat"],
                    ing["aliases"],
                ),
            )
            ingredient_ids[ing["name"]] = cursor.lastrowid
            print(f"  + {ing['name']} ({ing['category']})")
        except sqlite3.IntegrityError:
            # Get existing ID
            cursor.execute("SELECT id FROM generic_ingredients WHERE name = ?", (ing["name"],))
            row = cursor.fetchone()
            if row:
                ingredient_ids[ing["name"]] = row[0]

    # Refresh ingredient_ids for all ingredients
    cursor.execute("SELECT id, name FROM generic_ingredients")
    for row in cursor.fetchall():
        ingredient_ids[row[1]] = row[0]

    # Seed store products
    print(f"\nSeeding {len(STORE_PRODUCTS)} store products...")
    today = date.today().isoformat()

    for prod in STORE_PRODUCTS:
        ingredient_id = ingredient_ids.get(prod.get("ingredient_name"))

        try:
            cursor.execute(
                """
                INSERT OR REPLACE INTO pantry_products
                (barcode, name, brand, store, ingredient_id, category, subcategory, storage_type,
                 calories, protein, carbs, fat, fiber, sodium, sugar, saturated_fat,
                 package_weight_g, package_unit, price, price_per_kg, currency,
                 data_source, last_price_update)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
                (
                    prod["barcode"],
                    prod["name"],
                    prod["brand"],
                    prod["store"],
                    ingredient_id,
                    prod["category"],
                    prod["subcategory"],
                    prod["storage_type"],
                    prod["calories"],
                    prod["protein"],
                    prod["carbs"],
                    prod["fat"],
                    prod["fiber"],
                    prod["sodium"],
                    prod["sugar"],
                    prod["saturated_fat"],
                    prod["package_weight_g"],
                    prod["package_unit"],
                    prod["price"],
                    prod["price_per_kg"],
                    "EUR",
                    "manual",
                    today,
                ),
            )
            store_marker = {"aldi": "[A]", "lidl": "[L]", "rewe": "[R]"}.get(prod["store"], "[?]")
            print(f"  {store_marker} {prod['brand']} {prod['name']} - EUR {prod['price']}")
        except sqlite3.IntegrityError as e:
            print(f"  [!] Skipped (duplicate): {prod['name']}")

    conn.commit()

    # Print summary
    cursor.execute("SELECT COUNT(*) FROM generic_ingredients")
    ing_count = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM pantry_products")
    prod_count = cursor.fetchone()[0]

    cursor.execute("SELECT store, COUNT(*) FROM pantry_products GROUP BY store")
    store_counts = cursor.fetchall()

    print("\n" + "=" * 50)
    print("DATABASE SEEDED SUCCESSFULLY")
    print("=" * 50)
    print(f"Generic ingredients: {ing_count}")
    print(f"Store products: {prod_count}")
    print("\nProducts by store:")
    for store, count in store_counts:
        print(f"  {store.upper() if store else 'Unknown'}: {count}")

    conn.close()


if __name__ == "__main__":
    seed_database()
