"""
Seed data for Food App - Aldi-available ingredients and recipes
"""

import os
import sqlite3

DATABASE = os.path.join(os.path.dirname(__file__), "food.db")

# Common Aldi ingredients with nutrition data (per 100g)
INGREDIENTS = [
    # Proteins - Meat & Seafood
    {
        "name": "Chicken Breast",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 165,
        "protein": 31,
        "carbs": 0,
        "fat": 3.6,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Chicken Thighs",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 209,
        "protein": 26,
        "carbs": 0,
        "fat": 10.9,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Ground Beef 80/20",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 254,
        "protein": 17,
        "carbs": 0,
        "fat": 20,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Ground Turkey",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 149,
        "protein": 19,
        "carbs": 0,
        "fat": 8,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Italian Sausage",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 301,
        "protein": 16,
        "carbs": 1,
        "fat": 25,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Pork Chops",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 231,
        "protein": 25,
        "carbs": 0,
        "fat": 14,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Salmon Fillet",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "lb",
        "calories": 208,
        "protein": 20,
        "carbs": 0,
        "fat": 13,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Shrimp",
        "category": "protein",
        "aldi_section": "Frozen",
        "default_unit": "lb",
        "calories": 99,
        "protein": 24,
        "carbs": 0,
        "fat": 0.3,
        "fiber": 0,
        "grams_per_unit": 454,
    },
    {
        "name": "Bacon",
        "category": "protein",
        "aldi_section": "Meat & Seafood",
        "default_unit": "slice",
        "calories": 541,
        "protein": 37,
        "carbs": 1,
        "fat": 42,
        "fiber": 0,
        "grams_per_unit": 15,
    },
    # Produce - Vegetables
    {
        "name": "Onion",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 40,
        "protein": 1.1,
        "carbs": 9,
        "fat": 0.1,
        "fiber": 1.7,
        "grams_per_unit": 150,
    },
    {
        "name": "Garlic",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "clove",
        "calories": 149,
        "protein": 6.4,
        "carbs": 33,
        "fat": 0.5,
        "fiber": 2.1,
        "grams_per_unit": 5,
    },
    {
        "name": "Bell Pepper",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 31,
        "protein": 1,
        "carbs": 6,
        "fat": 0.3,
        "fiber": 2.1,
        "grams_per_unit": 150,
    },
    {
        "name": "Broccoli",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "cup",
        "calories": 34,
        "protein": 2.8,
        "carbs": 7,
        "fat": 0.4,
        "fiber": 2.6,
        "grams_per_unit": 91,
    },
    {
        "name": "Carrots",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 41,
        "protein": 0.9,
        "carbs": 10,
        "fat": 0.2,
        "fiber": 2.8,
        "grams_per_unit": 61,
    },
    {
        "name": "Celery",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "stalk",
        "calories": 6,
        "protein": 0.3,
        "carbs": 1.2,
        "fat": 0.1,
        "fiber": 0.6,
        "grams_per_unit": 40,
    },
    {
        "name": "Zucchini",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 17,
        "protein": 1.2,
        "carbs": 3,
        "fat": 0.3,
        "fiber": 1,
        "grams_per_unit": 200,
    },
    {
        "name": "Mushrooms",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "cup",
        "calories": 22,
        "protein": 3.1,
        "carbs": 3,
        "fat": 0.3,
        "fiber": 1,
        "grams_per_unit": 70,
    },
    {
        "name": "Spinach",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "cup",
        "calories": 23,
        "protein": 2.9,
        "carbs": 3.6,
        "fat": 0.4,
        "fiber": 2.2,
        "grams_per_unit": 30,
    },
    {
        "name": "Tomato",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 18,
        "protein": 0.9,
        "carbs": 3.9,
        "fat": 0.2,
        "fiber": 1.2,
        "grams_per_unit": 123,
    },
    {
        "name": "Potato",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 77,
        "protein": 2,
        "carbs": 17,
        "fat": 0.1,
        "fiber": 2.2,
        "grams_per_unit": 150,
    },
    {
        "name": "Green Beans",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "cup",
        "calories": 31,
        "protein": 1.8,
        "carbs": 7,
        "fat": 0.1,
        "fiber": 3.4,
        "grams_per_unit": 100,
    },
    {
        "name": "Romaine Lettuce",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "cup",
        "calories": 8,
        "protein": 0.6,
        "carbs": 1.5,
        "fat": 0.1,
        "fiber": 1,
        "grams_per_unit": 47,
    },
    {
        "name": "Cabbage",
        "category": "vegetable",
        "aldi_section": "Produce",
        "default_unit": "cup",
        "calories": 22,
        "protein": 1.1,
        "carbs": 5,
        "fat": 0.1,
        "fiber": 2,
        "grams_per_unit": 89,
    },
    # Produce - Fruits
    {
        "name": "Lemon",
        "category": "fruit",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 17,
        "protein": 0.6,
        "carbs": 5,
        "fat": 0.2,
        "fiber": 1.6,
        "grams_per_unit": 58,
    },
    {
        "name": "Lime",
        "category": "fruit",
        "aldi_section": "Produce",
        "default_unit": "medium",
        "calories": 20,
        "protein": 0.5,
        "carbs": 7,
        "fat": 0.1,
        "fiber": 1.9,
        "grams_per_unit": 67,
    },
    # Dairy & Eggs
    {
        "name": "Eggs",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "large",
        "calories": 155,
        "protein": 13,
        "carbs": 1.1,
        "fat": 11,
        "fiber": 0,
        "grams_per_unit": 50,
    },
    {
        "name": "Butter",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "tbsp",
        "calories": 717,
        "protein": 0.9,
        "carbs": 0.1,
        "fat": 81,
        "fiber": 0,
        "grams_per_unit": 14,
    },
    {
        "name": "Heavy Cream",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "cup",
        "calories": 340,
        "protein": 2.8,
        "carbs": 2.8,
        "fat": 36,
        "fiber": 0,
        "grams_per_unit": 240,
    },
    {
        "name": "Milk",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "cup",
        "calories": 61,
        "protein": 3.2,
        "carbs": 4.8,
        "fat": 3.3,
        "fiber": 0,
        "grams_per_unit": 244,
    },
    {
        "name": "Parmesan Cheese",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "cup",
        "calories": 431,
        "protein": 38,
        "carbs": 4,
        "fat": 29,
        "fiber": 0,
        "grams_per_unit": 100,
    },
    {
        "name": "Cheddar Cheese",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "cup",
        "calories": 403,
        "protein": 25,
        "carbs": 1.3,
        "fat": 33,
        "fiber": 0,
        "grams_per_unit": 113,
    },
    {
        "name": "Sour Cream",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "tbsp",
        "calories": 193,
        "protein": 2.4,
        "carbs": 4.6,
        "fat": 19,
        "fiber": 0,
        "grams_per_unit": 15,
    },
    {
        "name": "Cream Cheese",
        "category": "dairy",
        "aldi_section": "Dairy & Eggs",
        "default_unit": "oz",
        "calories": 342,
        "protein": 6,
        "carbs": 4,
        "fat": 34,
        "fiber": 0,
        "grams_per_unit": 28,
    },
    # Pantry Staples
    {
        "name": "White Rice",
        "category": "grain",
        "aldi_section": "Pantry",
        "default_unit": "cup",
        "calories": 130,
        "protein": 2.7,
        "carbs": 28,
        "fat": 0.3,
        "fiber": 0.4,
        "grams_per_unit": 185,
    },
    {
        "name": "Pasta",
        "category": "grain",
        "aldi_section": "Pantry",
        "default_unit": "oz",
        "calories": 371,
        "protein": 13,
        "carbs": 75,
        "fat": 1.5,
        "fiber": 3.2,
        "grams_per_unit": 28,
    },
    {
        "name": "Chicken Broth",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "cup",
        "calories": 10,
        "protein": 1,
        "carbs": 1,
        "fat": 0,
        "fiber": 0,
        "grams_per_unit": 240,
    },
    {
        "name": "Beef Broth",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "cup",
        "calories": 17,
        "protein": 3,
        "carbs": 0,
        "fat": 0.5,
        "fiber": 0,
        "grams_per_unit": 240,
    },
    {
        "name": "Diced Tomatoes",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "can",
        "calories": 18,
        "protein": 0.9,
        "carbs": 4,
        "fat": 0.2,
        "fiber": 1.2,
        "grams_per_unit": 400,
    },
    {
        "name": "Tomato Sauce",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "can",
        "calories": 29,
        "protein": 1.3,
        "carbs": 6,
        "fat": 0.2,
        "fiber": 1.5,
        "grams_per_unit": 227,
    },
    {
        "name": "Tomato Paste",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 82,
        "protein": 4.3,
        "carbs": 19,
        "fat": 0.5,
        "fiber": 4.1,
        "grams_per_unit": 16,
    },
    {
        "name": "Black Beans",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "can",
        "calories": 132,
        "protein": 8.9,
        "carbs": 24,
        "fat": 0.5,
        "fiber": 8.7,
        "grams_per_unit": 400,
    },
    {
        "name": "Kidney Beans",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "can",
        "calories": 127,
        "protein": 8.7,
        "carbs": 23,
        "fat": 0.5,
        "fiber": 6.4,
        "grams_per_unit": 400,
    },
    {
        "name": "Olive Oil",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 884,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "fiber": 0,
        "grams_per_unit": 14,
    },
    {
        "name": "Vegetable Oil",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 884,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "fiber": 0,
        "grams_per_unit": 14,
    },
    {
        "name": "Flour",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "cup",
        "calories": 364,
        "protein": 10,
        "carbs": 76,
        "fat": 1,
        "fiber": 2.7,
        "grams_per_unit": 125,
    },
    {
        "name": "Sugar",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 387,
        "protein": 0,
        "carbs": 100,
        "fat": 0,
        "fiber": 0,
        "grams_per_unit": 12.5,
    },
    {
        "name": "Brown Sugar",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 380,
        "protein": 0,
        "carbs": 98,
        "fat": 0,
        "fiber": 0,
        "grams_per_unit": 12,
    },
    {
        "name": "Soy Sauce",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 53,
        "protein": 8,
        "carbs": 5,
        "fat": 0,
        "fiber": 0.8,
        "grams_per_unit": 18,
    },
    {
        "name": "Worcestershire Sauce",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 78,
        "protein": 0,
        "carbs": 19,
        "fat": 0,
        "fiber": 0,
        "grams_per_unit": 17,
    },
    {
        "name": "Hot Sauce",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 3,
        "protein": 0,
        "carbs": 0.5,
        "fat": 0,
        "fiber": 0.1,
        "grams_per_unit": 5,
    },
    {
        "name": "Breadcrumbs",
        "category": "pantry",
        "aldi_section": "Pantry",
        "default_unit": "cup",
        "calories": 395,
        "protein": 13,
        "carbs": 72,
        "fat": 5,
        "fiber": 4.5,
        "grams_per_unit": 108,
    },
    # Spices & Seasonings
    {
        "name": "Salt",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 0,
        "protein": 0,
        "carbs": 0,
        "fat": 0,
        "fiber": 0,
        "grams_per_unit": 6,
    },
    {
        "name": "Black Pepper",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 251,
        "protein": 10,
        "carbs": 64,
        "fat": 3.3,
        "fiber": 25,
        "grams_per_unit": 2.3,
    },
    {
        "name": "Garlic Powder",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 331,
        "protein": 17,
        "carbs": 73,
        "fat": 0.7,
        "fiber": 9,
        "grams_per_unit": 3,
    },
    {
        "name": "Onion Powder",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 341,
        "protein": 10,
        "carbs": 79,
        "fat": 1,
        "fiber": 15,
        "grams_per_unit": 2.4,
    },
    {
        "name": "Paprika",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 282,
        "protein": 14,
        "carbs": 54,
        "fat": 13,
        "fiber": 34,
        "grams_per_unit": 2.3,
    },
    {
        "name": "Cumin",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 375,
        "protein": 18,
        "carbs": 44,
        "fat": 22,
        "fiber": 11,
        "grams_per_unit": 2.1,
    },
    {
        "name": "Chili Powder",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 282,
        "protein": 12,
        "carbs": 50,
        "fat": 14,
        "fiber": 34,
        "grams_per_unit": 2.6,
    },
    {
        "name": "Italian Seasoning",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 264,
        "protein": 9,
        "carbs": 52,
        "fat": 7,
        "fiber": 18,
        "grams_per_unit": 1,
    },
    {
        "name": "Oregano",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 265,
        "protein": 9,
        "carbs": 69,
        "fat": 4.3,
        "fiber": 43,
        "grams_per_unit": 1,
    },
    {
        "name": "Thyme",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tsp",
        "calories": 276,
        "protein": 9,
        "carbs": 64,
        "fat": 7.4,
        "fiber": 37,
        "grams_per_unit": 1,
    },
    {
        "name": "Bay Leaves",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "leaf",
        "calories": 313,
        "protein": 8,
        "carbs": 75,
        "fat": 8.4,
        "fiber": 26,
        "grams_per_unit": 0.6,
    },
    {
        "name": "Taco Seasoning",
        "category": "spice",
        "aldi_section": "Pantry",
        "default_unit": "tbsp",
        "calories": 280,
        "protein": 6,
        "carbs": 55,
        "fat": 5,
        "fiber": 6,
        "grams_per_unit": 8,
    },
    # Bakery
    {
        "name": "Bread",
        "category": "bakery",
        "aldi_section": "Bakery",
        "default_unit": "slice",
        "calories": 265,
        "protein": 9,
        "carbs": 49,
        "fat": 3.2,
        "fiber": 2.7,
        "grams_per_unit": 25,
    },
    {
        "name": "Tortillas",
        "category": "bakery",
        "aldi_section": "Bakery",
        "default_unit": "tortilla",
        "calories": 312,
        "protein": 8,
        "carbs": 52,
        "fat": 8,
        "fiber": 3,
        "grams_per_unit": 49,
    },
    {
        "name": "Taco Shells",
        "category": "bakery",
        "aldi_section": "Bakery",
        "default_unit": "shell",
        "calories": 489,
        "protein": 7,
        "carbs": 62,
        "fat": 24,
        "fiber": 4.5,
        "grams_per_unit": 13,
    },
    {
        "name": "French Bread",
        "category": "bakery",
        "aldi_section": "Bakery",
        "default_unit": "slice",
        "calories": 289,
        "protein": 9,
        "carbs": 56,
        "fat": 2.4,
        "fiber": 2.4,
        "grams_per_unit": 35,
    },
    # Frozen
    {
        "name": "Frozen Mixed Vegetables",
        "category": "frozen",
        "aldi_section": "Frozen",
        "default_unit": "cup",
        "calories": 59,
        "protein": 2.6,
        "carbs": 12,
        "fat": 0.2,
        "fiber": 4,
        "grams_per_unit": 150,
    },
    {
        "name": "Frozen Peas",
        "category": "frozen",
        "aldi_section": "Frozen",
        "default_unit": "cup",
        "calories": 62,
        "protein": 4,
        "carbs": 11,
        "fat": 0.4,
        "fiber": 4,
        "grams_per_unit": 134,
    },
    {
        "name": "Frozen Corn",
        "category": "frozen",
        "aldi_section": "Frozen",
        "default_unit": "cup",
        "calories": 86,
        "protein": 2.9,
        "carbs": 19,
        "fat": 0.5,
        "fiber": 2.4,
        "grams_per_unit": 164,
    },
]

# Recipes with step-by-step instructions
RECIPES = [
    {
        "name": "One-Pan Chicken & Rice",
        "description": "A complete meal cooked in one pan - juicy chicken over flavorful rice",
        "category": "main",
        "cuisine": "american",
        "prep_time_min": 10,
        "cook_time_min": 35,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Chicken Breast", "quantity": 1.5, "unit": "lb"},
            {"name": "White Rice", "quantity": 1.5, "unit": "cup"},
            {"name": "Chicken Broth", "quantity": 2.5, "unit": "cup"},
            {"name": "Onion", "quantity": 1, "unit": "medium", "notes": "diced"},
            {"name": "Garlic", "quantity": 3, "unit": "clove", "notes": "minced"},
            {"name": "Olive Oil", "quantity": 2, "unit": "tbsp"},
            {"name": "Paprika", "quantity": 1, "unit": "tsp"},
            {"name": "Garlic Powder", "quantity": 1, "unit": "tsp"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.5, "unit": "tsp"},
        ],
        "steps": [
            {
                "title": "Season the Chicken",
                "instruction": "Pat chicken breasts dry with paper towels. Mix paprika, garlic powder, salt, and pepper. Season both sides of chicken generously.",
                "duration_min": 3,
            },
            {
                "title": "Sear the Chicken",
                "instruction": "Heat olive oil in a large oven-safe skillet over medium-high heat. Add chicken and sear 3-4 minutes per side until golden brown. Remove and set aside.",
                "duration_min": 8,
                "timer_needed": True,
                "tips": "Don't move the chicken while searing for best browning",
            },
            {
                "title": "Saute Aromatics",
                "instruction": "In the same pan, add diced onion. Cook 3 minutes until softened. Add minced garlic and cook 30 seconds until fragrant.",
                "duration_min": 4,
            },
            {
                "title": "Toast the Rice",
                "instruction": "Add rice to the pan. Stir to coat in the flavored oil. Toast for 1-2 minutes until slightly golden.",
                "duration_min": 2,
            },
            {
                "title": "Add Broth",
                "instruction": "Pour in chicken broth. Scrape up any browned bits from the bottom. Bring to a boil.",
                "duration_min": 2,
            },
            {
                "title": "Nestle Chicken",
                "instruction": "Place seared chicken breasts on top of the rice. Reduce heat to low. Cover with tight-fitting lid.",
                "duration_min": 1,
            },
            {
                "title": "Simmer",
                "instruction": "Let simmer covered for 18-20 minutes until rice is tender and chicken reaches 165F internal temp.",
                "duration_min": 20,
                "timer_needed": True,
                "tips": "Don't lift the lid during cooking!",
            },
            {
                "title": "Rest and Serve",
                "instruction": "Remove from heat. Let rest covered 5 minutes. Fluff rice with fork and serve.",
                "duration_min": 5,
            },
        ],
    },
    {
        "name": "Classic Beef Tacos",
        "description": "Quick and flavorful ground beef tacos with all the fixings",
        "category": "main",
        "cuisine": "mexican",
        "prep_time_min": 10,
        "cook_time_min": 15,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Ground Beef 80/20", "quantity": 1, "unit": "lb"},
            {"name": "Taco Seasoning", "quantity": 2, "unit": "tbsp"},
            {"name": "Onion", "quantity": 0.5, "unit": "medium", "notes": "diced"},
            {"name": "Garlic", "quantity": 2, "unit": "clove", "notes": "minced"},
            {"name": "Taco Shells", "quantity": 8, "unit": "shell"},
            {"name": "Cheddar Cheese", "quantity": 1, "unit": "cup", "notes": "shredded"},
            {"name": "Tomato", "quantity": 2, "unit": "medium", "notes": "diced"},
            {"name": "Romaine Lettuce", "quantity": 2, "unit": "cup", "notes": "shredded"},
            {"name": "Sour Cream", "quantity": 4, "unit": "tbsp"},
        ],
        "steps": [
            {
                "title": "Brown the Beef",
                "instruction": "Heat a large skillet over medium-high heat. Add ground beef, breaking it up with a spatula. Cook until browned, about 5-7 minutes.",
                "duration_min": 7,
                "timer_needed": True,
            },
            {
                "title": "Add Aromatics",
                "instruction": "Push beef to one side. Add diced onion to the empty side. Cook 2 minutes. Add garlic, cook 30 seconds. Mix together.",
                "duration_min": 3,
            },
            {
                "title": "Season",
                "instruction": "Sprinkle taco seasoning over the beef. Add 1/4 cup water. Stir to combine. Simmer 3-4 minutes until thickened.",
                "duration_min": 4,
                "tips": "Add more water if it gets too dry",
            },
            {
                "title": "Warm Shells",
                "instruction": "Warm taco shells according to package directions (usually 5 minutes in 325F oven).",
                "duration_min": 5,
            },
            {
                "title": "Assemble Tacos",
                "instruction": "Fill each shell with beef mixture. Top with cheese, tomato, lettuce, and sour cream.",
                "duration_min": 3,
            },
        ],
    },
    {
        "name": "Sheet Pan Sausage & Vegetables",
        "description": "Easy one-pan dinner with Italian sausage and roasted vegetables",
        "category": "main",
        "cuisine": "american",
        "prep_time_min": 15,
        "cook_time_min": 30,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Italian Sausage", "quantity": 1.5, "unit": "lb"},
            {"name": "Bell Pepper", "quantity": 3, "unit": "medium", "notes": "sliced"},
            {"name": "Onion", "quantity": 1, "unit": "medium", "notes": "sliced"},
            {"name": "Zucchini", "quantity": 2, "unit": "medium", "notes": "half-moons"},
            {"name": "Olive Oil", "quantity": 3, "unit": "tbsp"},
            {"name": "Italian Seasoning", "quantity": 1, "unit": "tsp"},
            {"name": "Garlic Powder", "quantity": 1, "unit": "tsp"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.5, "unit": "tsp"},
        ],
        "steps": [
            {
                "title": "Preheat Oven",
                "instruction": "Preheat oven to 400F (200C). Line a large sheet pan with parchment paper or foil.",
                "duration_min": 2,
            },
            {
                "title": "Prep Vegetables",
                "instruction": "Cut bell peppers into strips. Slice onion into wedges. Cut zucchini into half-moons (about 1/2 inch thick).",
                "duration_min": 8,
            },
            {
                "title": "Season Vegetables",
                "instruction": "Toss vegetables with 2 tbsp olive oil, Italian seasoning, garlic powder, salt, and pepper. Spread on sheet pan.",
                "duration_min": 3,
            },
            {
                "title": "Add Sausage",
                "instruction": "Cut sausage into 2-inch pieces. Nestle among the vegetables. Drizzle with remaining olive oil.",
                "duration_min": 2,
            },
            {
                "title": "Roast",
                "instruction": "Roast for 25-30 minutes, flipping sausage halfway through, until sausage is cooked through and vegetables are tender and slightly charred.",
                "duration_min": 30,
                "timer_needed": True,
                "tips": "Internal temp of sausage should reach 160F",
            },
        ],
    },
    {
        "name": "Spaghetti with Meat Sauce",
        "description": "Classic Italian-American comfort food with a rich tomato meat sauce",
        "category": "main",
        "cuisine": "italian",
        "prep_time_min": 10,
        "cook_time_min": 25,
        "servings": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Pasta", "quantity": 16, "unit": "oz"},
            {"name": "Ground Beef 80/20", "quantity": 1, "unit": "lb"},
            {"name": "Onion", "quantity": 1, "unit": "medium", "notes": "diced"},
            {"name": "Garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "Diced Tomatoes", "quantity": 1, "unit": "can"},
            {"name": "Tomato Sauce", "quantity": 1, "unit": "can"},
            {"name": "Tomato Paste", "quantity": 2, "unit": "tbsp"},
            {"name": "Italian Seasoning", "quantity": 2, "unit": "tsp"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.5, "unit": "tsp"},
            {"name": "Olive Oil", "quantity": 2, "unit": "tbsp"},
            {
                "name": "Parmesan Cheese",
                "quantity": 0.5,
                "unit": "cup",
                "notes": "grated, for serving",
            },
        ],
        "steps": [
            {
                "title": "Start Pasta Water",
                "instruction": "Fill a large pot with water, add generous salt, and bring to boil over high heat.",
                "duration_min": 2,
            },
            {
                "title": "Brown Beef",
                "instruction": "Heat olive oil in a large skillet over medium-high heat. Add ground beef, breaking up with spatula. Cook until browned, 5-6 minutes. Drain excess fat.",
                "duration_min": 6,
            },
            {
                "title": "Saute Aromatics",
                "instruction": "Add diced onion to the beef. Cook 3 minutes until soft. Add garlic, cook 1 minute until fragrant.",
                "duration_min": 4,
            },
            {
                "title": "Build Sauce",
                "instruction": "Add diced tomatoes, tomato sauce, and tomato paste. Stir in Italian seasoning, salt, and pepper. Bring to simmer.",
                "duration_min": 3,
            },
            {
                "title": "Simmer Sauce",
                "instruction": "Reduce heat to low. Let sauce simmer 15 minutes, stirring occasionally.",
                "duration_min": 15,
                "timer_needed": True,
                "tips": "Longer simmer = deeper flavor",
            },
            {
                "title": "Cook Pasta",
                "instruction": "Cook pasta according to package directions until al dente. Reserve 1/2 cup pasta water before draining.",
                "duration_min": 10,
                "timer_needed": True,
            },
            {
                "title": "Combine and Serve",
                "instruction": "Toss drained pasta with meat sauce. Add pasta water if needed to loosen. Serve topped with Parmesan.",
                "duration_min": 2,
            },
        ],
    },
    {
        "name": "Honey Garlic Chicken Stir-Fry",
        "description": "Quick Asian-inspired stir-fry with tender chicken and crisp vegetables",
        "category": "main",
        "cuisine": "asian",
        "prep_time_min": 15,
        "cook_time_min": 15,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {
                "name": "Chicken Breast",
                "quantity": 1.5,
                "unit": "lb",
                "notes": "cut into 1-inch pieces",
            },
            {"name": "Broccoli", "quantity": 3, "unit": "cup", "notes": "florets"},
            {"name": "Bell Pepper", "quantity": 2, "unit": "medium", "notes": "sliced"},
            {"name": "Garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "Soy Sauce", "quantity": 4, "unit": "tbsp"},
            {"name": "Vegetable Oil", "quantity": 3, "unit": "tbsp"},
            {"name": "Brown Sugar", "quantity": 2, "unit": "tbsp"},
            {"name": "Chicken Broth", "quantity": 0.25, "unit": "cup"},
            {"name": "White Rice", "quantity": 2, "unit": "cup", "notes": "cooked, for serving"},
        ],
        "steps": [
            {
                "title": "Make Sauce",
                "instruction": "Whisk together soy sauce, brown sugar, and chicken broth in a small bowl. Set aside.",
                "duration_min": 2,
            },
            {
                "title": "Cook Chicken",
                "instruction": "Heat 2 tbsp oil in wok or large skillet over high heat. Add chicken in single layer. Cook 3-4 minutes per side until golden and cooked through. Remove to plate.",
                "duration_min": 8,
                "tips": "Work in batches to avoid crowding",
            },
            {
                "title": "Stir-Fry Vegetables",
                "instruction": "Add remaining oil. Add broccoli and bell peppers. Stir-fry 3-4 minutes until crisp-tender.",
                "duration_min": 4,
            },
            {
                "title": "Add Garlic",
                "instruction": "Push vegetables to sides. Add garlic to center. Cook 30 seconds until fragrant.",
                "duration_min": 1,
            },
            {
                "title": "Combine",
                "instruction": "Return chicken to pan. Pour sauce over everything. Toss to coat. Cook 1-2 minutes until sauce thickens slightly.",
                "duration_min": 2,
            },
            {
                "title": "Serve",
                "instruction": "Serve immediately over hot rice.",
                "duration_min": 1,
            },
        ],
    },
    {
        "name": "Baked Chicken Thighs",
        "description": "Crispy-skinned, juicy chicken thighs - simple and delicious",
        "category": "main",
        "cuisine": "american",
        "prep_time_min": 5,
        "cook_time_min": 45,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Chicken Thighs", "quantity": 2, "unit": "lb", "notes": "bone-in, skin-on"},
            {"name": "Olive Oil", "quantity": 2, "unit": "tbsp"},
            {"name": "Garlic Powder", "quantity": 1, "unit": "tsp"},
            {"name": "Paprika", "quantity": 1, "unit": "tsp"},
            {"name": "Onion Powder", "quantity": 0.5, "unit": "tsp"},
            {"name": "Thyme", "quantity": 0.5, "unit": "tsp"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.5, "unit": "tsp"},
        ],
        "steps": [
            {
                "title": "Preheat Oven",
                "instruction": "Preheat oven to 425F (220C). Line a baking sheet with foil for easy cleanup.",
                "duration_min": 2,
            },
            {
                "title": "Dry Chicken",
                "instruction": "Pat chicken thighs very dry with paper towels. This is key for crispy skin!",
                "duration_min": 2,
                "tips": "Really get them dry - moisture is the enemy of crispy skin",
            },
            {
                "title": "Season",
                "instruction": "Mix garlic powder, paprika, onion powder, thyme, salt, and pepper. Rub chicken with olive oil, then coat with spice mixture.",
                "duration_min": 3,
            },
            {
                "title": "Arrange on Pan",
                "instruction": "Place chicken thighs skin-side up on prepared baking sheet, not touching each other.",
                "duration_min": 1,
            },
            {
                "title": "Bake",
                "instruction": "Bake 40-45 minutes until skin is crispy and internal temp reaches 165F.",
                "duration_min": 45,
                "timer_needed": True,
            },
            {
                "title": "Rest",
                "instruction": "Let rest 5 minutes before serving.",
                "duration_min": 5,
            },
        ],
    },
    {
        "name": "Classic Chili",
        "description": "Hearty beef and bean chili - perfect for meal prep",
        "category": "main",
        "cuisine": "american",
        "prep_time_min": 15,
        "cook_time_min": 45,
        "servings": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Ground Beef 80/20", "quantity": 2, "unit": "lb"},
            {"name": "Onion", "quantity": 1, "unit": "medium", "notes": "diced"},
            {"name": "Bell Pepper", "quantity": 1, "unit": "medium", "notes": "diced"},
            {"name": "Garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "Diced Tomatoes", "quantity": 2, "unit": "can"},
            {"name": "Kidney Beans", "quantity": 2, "unit": "can", "notes": "drained and rinsed"},
            {"name": "Tomato Paste", "quantity": 3, "unit": "tbsp"},
            {"name": "Beef Broth", "quantity": 1, "unit": "cup"},
            {"name": "Chili Powder", "quantity": 3, "unit": "tbsp"},
            {"name": "Cumin", "quantity": 1, "unit": "tbsp"},
            {"name": "Paprika", "quantity": 1, "unit": "tsp"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {
                "name": "Cheddar Cheese",
                "quantity": 1,
                "unit": "cup",
                "notes": "shredded, for serving",
            },
            {"name": "Sour Cream", "quantity": 0.5, "unit": "cup", "notes": "for serving"},
        ],
        "steps": [
            {
                "title": "Brown Beef",
                "instruction": "In a large pot or Dutch oven over medium-high heat, brown ground beef, breaking into crumbles. Drain excess fat.",
                "duration_min": 8,
            },
            {
                "title": "Saute Vegetables",
                "instruction": "Add onion and bell pepper. Cook 5 minutes until softened. Add garlic, cook 1 minute.",
                "duration_min": 6,
            },
            {
                "title": "Add Spices",
                "instruction": "Stir in chili powder, cumin, paprika, and salt. Cook 1 minute to toast spices.",
                "duration_min": 1,
                "tips": "Toasting spices brings out their flavor",
            },
            {
                "title": "Add Liquids",
                "instruction": "Add diced tomatoes, tomato paste, and beef broth. Stir to combine.",
                "duration_min": 2,
            },
            {
                "title": "Add Beans",
                "instruction": "Stir in kidney beans. Bring to a boil.",
                "duration_min": 2,
            },
            {
                "title": "Simmer",
                "instruction": "Reduce heat to low. Simmer uncovered 30-45 minutes, stirring occasionally, until thickened.",
                "duration_min": 35,
                "timer_needed": True,
                "tips": "Longer simmer = better flavor",
            },
            {
                "title": "Serve",
                "instruction": "Ladle into bowls. Top with shredded cheese and sour cream.",
                "duration_min": 2,
            },
        ],
    },
    {
        "name": "Garlic Butter Salmon",
        "description": "Restaurant-quality salmon in under 20 minutes",
        "category": "main",
        "cuisine": "american",
        "prep_time_min": 5,
        "cook_time_min": 12,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Salmon Fillet", "quantity": 1.5, "unit": "lb", "notes": "4 portions"},
            {"name": "Butter", "quantity": 4, "unit": "tbsp"},
            {"name": "Garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "Lemon", "quantity": 1, "unit": "medium", "notes": "juiced and zested"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.5, "unit": "tsp"},
            {"name": "Thyme", "quantity": 0.5, "unit": "tsp"},
        ],
        "steps": [
            {
                "title": "Prep Salmon",
                "instruction": "Pat salmon dry. Season both sides with salt and pepper.",
                "duration_min": 2,
            },
            {
                "title": "Make Garlic Butter",
                "instruction": "Melt butter in a large oven-safe skillet over medium heat. Add garlic, cook 1 minute. Stir in lemon zest and thyme.",
                "duration_min": 2,
            },
            {
                "title": "Sear Salmon",
                "instruction": "Place salmon skin-side up in pan. Sear 3-4 minutes until golden. Flip carefully.",
                "duration_min": 4,
                "timer_needed": True,
            },
            {
                "title": "Finish Cooking",
                "instruction": "Spoon garlic butter over salmon. Cook another 3-4 minutes until salmon flakes easily.",
                "duration_min": 4,
                "tips": "Salmon is done at 145F internal temp",
            },
            {
                "title": "Serve",
                "instruction": "Squeeze lemon juice over salmon. Serve with pan sauce spooned on top.",
                "duration_min": 1,
            },
        ],
    },
    # SIDES
    {
        "name": "Roasted Broccoli",
        "description": "Simple roasted broccoli with crispy edges",
        "category": "side",
        "cuisine": "american",
        "prep_time_min": 5,
        "cook_time_min": 20,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Broccoli", "quantity": 6, "unit": "cup", "notes": "florets"},
            {"name": "Olive Oil", "quantity": 3, "unit": "tbsp"},
            {"name": "Garlic Powder", "quantity": 0.5, "unit": "tsp"},
            {"name": "Salt", "quantity": 0.5, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.25, "unit": "tsp"},
            {"name": "Lemon", "quantity": 0.5, "unit": "medium", "notes": "juiced"},
            {"name": "Parmesan Cheese", "quantity": 0.25, "unit": "cup", "notes": "grated"},
        ],
        "steps": [
            {
                "title": "Preheat Oven",
                "instruction": "Preheat oven to 425F (220C). Line baking sheet with parchment.",
                "duration_min": 2,
            },
            {
                "title": "Season Broccoli",
                "instruction": "Toss broccoli florets with olive oil, garlic powder, salt, and pepper.",
                "duration_min": 2,
            },
            {
                "title": "Arrange on Pan",
                "instruction": "Spread in single layer on baking sheet. Don't overcrowd!",
                "duration_min": 1,
                "tips": "Overcrowding causes steaming instead of roasting",
            },
            {
                "title": "Roast",
                "instruction": "Roast 18-20 minutes until edges are crispy and browned.",
                "duration_min": 20,
                "timer_needed": True,
            },
            {
                "title": "Finish",
                "instruction": "Drizzle with lemon juice and sprinkle with Parmesan.",
                "duration_min": 1,
            },
        ],
    },
    {
        "name": "Garlic Mashed Potatoes",
        "description": "Creamy, buttery mashed potatoes with roasted garlic",
        "category": "side",
        "cuisine": "american",
        "prep_time_min": 10,
        "cook_time_min": 25,
        "servings": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Potato", "quantity": 3, "unit": "lb", "notes": "peeled and cubed"},
            {"name": "Butter", "quantity": 6, "unit": "tbsp"},
            {"name": "Heavy Cream", "quantity": 0.5, "unit": "cup"},
            {"name": "Garlic", "quantity": 6, "unit": "clove", "notes": "minced"},
            {"name": "Salt", "quantity": 1, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.5, "unit": "tsp"},
        ],
        "steps": [
            {
                "title": "Boil Potatoes",
                "instruction": "Place cubed potatoes in large pot. Cover with cold water. Add salt. Bring to boil, then simmer 15-20 minutes until fork-tender.",
                "duration_min": 20,
                "timer_needed": True,
            },
            {
                "title": "Make Garlic Butter",
                "instruction": "While potatoes cook, melt butter in small pan. Add garlic, cook 2 minutes on low until fragrant. Add cream, warm through.",
                "duration_min": 5,
            },
            {
                "title": "Drain Potatoes",
                "instruction": "Drain potatoes well. Return to pot over low heat for 1 minute to dry out.",
                "duration_min": 2,
            },
            {
                "title": "Mash",
                "instruction": "Add garlic butter mixture to potatoes. Mash until smooth. Season with salt and pepper.",
                "duration_min": 3,
                "tips": "Don't overmix or potatoes become gluey",
            },
        ],
    },
    {
        "name": "Steamed Green Beans",
        "description": "Simple buttered green beans",
        "category": "side",
        "cuisine": "american",
        "prep_time_min": 5,
        "cook_time_min": 8,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Green Beans", "quantity": 1, "unit": "lb", "notes": "trimmed"},
            {"name": "Butter", "quantity": 2, "unit": "tbsp"},
            {"name": "Garlic", "quantity": 2, "unit": "clove", "notes": "minced"},
            {"name": "Salt", "quantity": 0.5, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.25, "unit": "tsp"},
            {"name": "Lemon", "quantity": 0.5, "unit": "medium", "notes": "juiced"},
        ],
        "steps": [
            {
                "title": "Steam Beans",
                "instruction": "Add 1 inch water to pot with steamer basket. Bring to boil. Add green beans, cover, steam 5-7 minutes until crisp-tender.",
                "duration_min": 7,
                "timer_needed": True,
            },
            {
                "title": "Make Garlic Butter",
                "instruction": "Meanwhile, melt butter in small pan. Add garlic, cook 1 minute.",
                "duration_min": 2,
            },
            {
                "title": "Toss and Serve",
                "instruction": "Drain beans. Toss with garlic butter, salt, pepper, and lemon juice.",
                "duration_min": 2,
            },
        ],
    },
    {
        "name": "Simple Rice Pilaf",
        "description": "Flavorful rice cooked in broth with aromatics",
        "category": "side",
        "cuisine": "american",
        "prep_time_min": 5,
        "cook_time_min": 20,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "White Rice", "quantity": 1.5, "unit": "cup"},
            {"name": "Chicken Broth", "quantity": 2.5, "unit": "cup"},
            {"name": "Butter", "quantity": 2, "unit": "tbsp"},
            {"name": "Onion", "quantity": 0.5, "unit": "medium", "notes": "diced"},
            {"name": "Garlic", "quantity": 2, "unit": "clove", "notes": "minced"},
            {"name": "Salt", "quantity": 0.5, "unit": "tsp"},
            {"name": "Bay Leaves", "quantity": 1, "unit": "leaf"},
        ],
        "steps": [
            {
                "title": "Saute Aromatics",
                "instruction": "Melt butter in saucepan over medium heat. Add onion, cook 3 minutes. Add garlic, cook 1 minute.",
                "duration_min": 4,
            },
            {
                "title": "Toast Rice",
                "instruction": "Add rice. Stir to coat in butter. Toast 2 minutes until slightly golden.",
                "duration_min": 2,
            },
            {
                "title": "Add Broth",
                "instruction": "Add chicken broth, salt, and bay leaf. Bring to boil.",
                "duration_min": 2,
            },
            {
                "title": "Simmer",
                "instruction": "Reduce to low, cover tightly. Simmer 18 minutes without lifting lid.",
                "duration_min": 18,
                "timer_needed": True,
                "tips": "Don't peek!",
            },
            {
                "title": "Rest and Fluff",
                "instruction": "Remove from heat. Let rest 5 minutes. Remove bay leaf, fluff with fork.",
                "duration_min": 5,
            },
        ],
    },
    {
        "name": "Caesar Salad",
        "description": "Classic Caesar salad with homemade dressing",
        "category": "side",
        "cuisine": "american",
        "prep_time_min": 15,
        "cook_time_min": 0,
        "servings": 4,
        "difficulty": "easy",
        "ingredients": [
            {"name": "Romaine Lettuce", "quantity": 8, "unit": "cup", "notes": "chopped"},
            {"name": "Parmesan Cheese", "quantity": 0.5, "unit": "cup", "notes": "shaved"},
            {"name": "Olive Oil", "quantity": 0.25, "unit": "cup"},
            {"name": "Lemon", "quantity": 1, "unit": "medium", "notes": "juiced"},
            {"name": "Garlic", "quantity": 2, "unit": "clove", "notes": "minced"},
            {"name": "Worcestershire Sauce", "quantity": 1, "unit": "tsp"},
            {"name": "Salt", "quantity": 0.25, "unit": "tsp"},
            {"name": "Black Pepper", "quantity": 0.25, "unit": "tsp"},
            {"name": "Bread", "quantity": 2, "unit": "slice", "notes": "cubed for croutons"},
        ],
        "steps": [
            {
                "title": "Make Dressing",
                "instruction": "Whisk olive oil, lemon juice, minced garlic, Worcestershire, salt, and pepper in small bowl.",
                "duration_min": 3,
            },
            {
                "title": "Make Croutons (Optional)",
                "instruction": "Toast bread cubes in dry pan or under broiler until golden.",
                "duration_min": 5,
            },
            {
                "title": "Assemble Salad",
                "instruction": "Place romaine in large bowl. Drizzle with dressing, toss to coat.",
                "duration_min": 2,
            },
            {
                "title": "Finish",
                "instruction": "Top with Parmesan shavings and croutons. Serve immediately.",
                "duration_min": 1,
            },
        ],
    },
    {
        "name": "Garlic Bread",
        "description": "Crispy, buttery garlic bread",
        "category": "side",
        "cuisine": "italian",
        "prep_time_min": 5,
        "cook_time_min": 10,
        "servings": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "French Bread", "quantity": 1, "unit": "loaf"},
            {"name": "Butter", "quantity": 6, "unit": "tbsp", "notes": "softened"},
            {"name": "Garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "Italian Seasoning", "quantity": 0.5, "unit": "tsp"},
            {"name": "Parmesan Cheese", "quantity": 0.25, "unit": "cup", "notes": "grated"},
            {"name": "Salt", "quantity": 0.25, "unit": "tsp"},
        ],
        "steps": [
            {
                "title": "Preheat Oven",
                "instruction": "Preheat oven to 400F (200C).",
                "duration_min": 2,
            },
            {
                "title": "Make Garlic Butter",
                "instruction": "Mix softened butter, minced garlic, Italian seasoning, Parmesan, and salt.",
                "duration_min": 2,
            },
            {
                "title": "Prep Bread",
                "instruction": "Slice bread in half lengthwise. Spread garlic butter evenly on cut sides.",
                "duration_min": 2,
            },
            {
                "title": "Bake",
                "instruction": "Place on baking sheet, cut side up. Bake 10-12 minutes until golden and crispy.",
                "duration_min": 12,
                "timer_needed": True,
            },
            {
                "title": "Slice and Serve",
                "instruction": "Cut into slices and serve warm.",
                "duration_min": 1,
            },
        ],
    },
]


def seed_database():
    """Seed the database with ingredients and recipes."""
    conn = sqlite3.connect(DATABASE)
    cursor = conn.cursor()

    print("Seeding ingredients...")
    for ing in INGREDIENTS:
        cursor.execute(
            """
            INSERT OR IGNORE INTO ingredients
            (name, category, aldi_section, default_unit, calories_per_100g, protein_per_100g,
             carbs_per_100g, fat_per_100g, fiber_per_100g, grams_per_unit)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            [
                ing["name"],
                ing["category"],
                ing["aldi_section"],
                ing["default_unit"],
                ing["calories"],
                ing["protein"],
                ing["carbs"],
                ing["fat"],
                ing["fiber"],
                ing.get("grams_per_unit", 100),
            ],
        )
    print(f"  Added {len(INGREDIENTS)} ingredients")

    print("Seeding recipes...")
    for recipe in RECIPES:
        # Insert recipe
        cursor.execute(
            """
            INSERT INTO recipes (name, description, category, cuisine, prep_time_min, cook_time_min, servings, difficulty)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
            [
                recipe["name"],
                recipe["description"],
                recipe["category"],
                recipe["cuisine"],
                recipe["prep_time_min"],
                recipe["cook_time_min"],
                recipe["servings"],
                recipe["difficulty"],
            ],
        )
        recipe_id = cursor.lastrowid

        # Insert ingredients
        for ing in recipe["ingredients"]:
            # Find ingredient ID
            cursor.execute("SELECT id FROM ingredients WHERE name = ?", [ing["name"]])
            result = cursor.fetchone()
            if result:
                ingredient_id = result[0]
                cursor.execute(
                    """
                    INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit, notes)
                    VALUES (?, ?, ?, ?, ?)
                """,
                    [recipe_id, ingredient_id, ing["quantity"], ing["unit"], ing.get("notes")],
                )

        # Insert steps
        for i, step in enumerate(recipe["steps"], 1):
            cursor.execute(
                """
                INSERT INTO cooking_steps (recipe_id, step_number, title, instruction, duration_min, tips, timer_needed)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
                [
                    recipe_id,
                    i,
                    step["title"],
                    step["instruction"],
                    step.get("duration_min"),
                    step.get("tips"),
                    step.get("timer_needed", 0),
                ],
            )

        print(f"  Added: {recipe['name']}")

    conn.commit()
    conn.close()
    print("\nDatabase seeded successfully!")


if __name__ == "__main__":
    seed_database()
